### ISSUE TITLE
cifar_ard loss is nan.

### ISSUE THREAD

**Issue by toshi2k2** [Leensman/VarDropPytorch#2]
Ran the cifar_ard code - the train and test loss shows nan around 6th epoch. Are there any issues with the code?

**Comment by HolyBayes** [comment]
Hi! Such an issue takes a place because of wrong initialization of sigmas. Try to initialize it with a smaller values. I'll try to use more flexible initialization of it soon

**Comment by HolyBayes** [comment]
Fixed
