### ISSUE TITLE
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported

### ISSUE THREAD

**Issue by bambi2511** [Leensman/VarDropPytorch#3]
Hi,

I am trying to install pytorch_ard to test variational dropout, but whatever the install of the library, the test script constantly fails with the same error:

Sparsification ratio: 11.880%
Traceback (most recent call last):
...
/pytorch_ard-0.2.1-py3.6.egg/torch_ard/torch_ard.py", line 70, in _update_sparse_weights
  File "/home/supercalculateur/environment/torch_ard/lib/python3.6/site-packages/torch/tensor.py", line 325, in __rsub__
    return _C._VariableFunctions.rsub(self, other)
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `bitwise_not()` operator instead.

I tried : 
- to install everything with pypi
- to docwngrade torch to 1.1
- to install pytorch_ard, from source  (with gcc 5.5 instead of standard 7.4)

It must be silly, but I still can't figure out why I always get this error (either operation is not defined or tensor is wrongly a boolean one)  
 
I use nvidia driver 430.26 with CUDA Version: 10.2 on ubuntu 18.04

Regards,

Francois

**Comment by HolyBayes** [comment]
Thanks for your comment! Fixed
