### ISSUE TITLE
Cannot create Conv2dARD with bias=True

### ISSUE THREAD

**Issue by Animatory** [Leensman/VarDropPytorch#4]
Due to Conv2dARD creates bias before initialization of the parent class (torch.nn.Conv2d)  
```python       
if bias: bias = Parameter(torch.Tensor(out_channels))
else: bias = None  
super(Conv2dARD, self).__init__(in_channels, out_channels, kernel_size, stride,  
           padding, dilation, groups, bias)
```
torch.Tensor goes into In super().__init__ therefore these lines in `torch/nn/modules/conv.py` are failed
```python
42 if bias:
43    self.bias = Parameter(torch.Tensor(out_channels))
```
with `RuntimeError: bool value of Tensor with more than one value is ambiguous`

Python 3.7.4
PyTorch 1.2

**Comment by N2606** [comment]
Hi @Animatory , same problem here. Have you fixed it?

**Comment by HolyBayes** [comment]
Fixed! Conv2dARD.bias removed - it immediately crashes convergence. Use batchnorm instead
