### ISSUE TITLE
mnist_ard loss is nan

### ISSUE THREAD

**Issue by N2606** [Leensman/VarDropPytorch#5]
Hi, thanks for the works.
I ran the mnist_ard and the loss is always nan regardless how I initialize log_sigma2.
Did anyone train successfully?

**Comment by HolyBayes** [comment]
Hi! Thanks for your comment. Fixed

**Comment by lumosity4tpj** [comment]
@N2606 
how to slove the initialize problem? When I change the initial value of log_sigma2, the loss can become non-Nan. However, loss is almost constant, resulting in the failure of model convergence.
