### ISSUE TITLE
Cannot create LinearARD with bias=False

### ISSUE THREAD

**Issue by ideafang** [Leensman/VarDropPytorch#8]
The code got `TypeError` when I run the `examples/boston_ard.py` with no bias LinearARD layers.

I changed the LinearARD in DenseModelARD to no bias:
```
self.l1 = nn_ard.LinearARD(input_shape, hidden_size, bias=False)
self.l2 = nn_ard.LinearARD(hidden_size, output_shape, bias=False)
```
then, `examples/boston_ard.py` is failed with `TypeError: unsupported operand type(s) for +=: 'Tensor' and 'NoneType`

It may be necessary to determine whether `bias=False` in the line 36 and 39 of `torch_ard.py` 
```
output += self.bias
...
output = F.linear(input, W) + self.bias
```

**Comment by HolyBayes** [comment]
Thank you! Fixed
